set(_CATKIN_CURRENT_PACKAGE "lugo")
set(lugo_VERSION "0.0.0")
set(lugo_MAINTAINER "fldec <fldec@todo.todo>")
set(lugo_PACKAGE_FORMAT "2")
set(lugo_BUILD_DEPENDS "roscpp" "rospy" "std_msgs" "message_generation")
set(lugo_BUILD_EXPORT_DEPENDS "roscpp" "rospy" "std_msgs")
set(lugo_BUILDTOOL_DEPENDS "catkin")
set(lugo_BUILDTOOL_EXPORT_DEPENDS )
set(lugo_EXEC_DEPENDS "roscpp" "rospy" "std_msgs" "message_generation" "message_runtime")
set(lugo_RUN_DEPENDS "roscpp" "rospy" "std_msgs" "message_generation" "message_runtime")
set(lugo_TEST_DEPENDS )
set(lugo_DOC_DEPENDS )
set(lugo_URL_WEBSITE "")
set(lugo_URL_BUGTRACKER "")
set(lugo_URL_REPOSITORY "")
set(lugo_DEPRECATED "")